name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [blacksmith-4vcpu-ubuntu-2404, windows-latest, blacksmith-6vcpu-macos-15]

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Build
        run: cargo build --verbose
        working-directory: ./bdgm
      - name: Run tests
        run: cargo test --verbose
        working-directory: ./bdgm

      - name: Build bdgm-play
        run: cargo build
        working-directory: ./bdgm/bdgm-play
      - name: Build bdgm-build
        run: cargo build
        working-directory: ./bdgm/bdgm-build
